---
version: 2.0
jobs:
  csharp:
    docker: googleapis/artman:latest
    steps:
      - checkout
      - run: Install latest artman
        command: |
          pip uninstall googleapis-artman
          pip install /usr/src/artman/
      - run: Build: Pub/Sub (C#)
        command: artman --api=pubsub --language=csharp --publish=noop
      - run: Build Speech (C#)
        command: artman --api=speech --language=csharp --publish=noop
    working_directory: /usr/src/artman/

  go:
    docker: googleapis/artman:latest
    steps:
      - checkout
      - run: Install latest artman
        command: |
          pip uninstall googleapis-artman
          pip install /usr/src/artman/
      - run: Build: Pub/Sub (Go)
        command: artman --api=pubsub --language=go --publish=noop
      - run: Build Speech (Go)
        command: artman --api=speech --language=go --publish=noop
    working_directory: /usr/src/artman/

  java:
    docker: googleapis/artman:latest
    steps:
      - checkout
      - run: Install latest artman
        command: |
          pip uninstall googleapis-artman
          pip install /usr/src/artman/
      - run: Build: Pub/Sub (Java)
        command: artman --api=pubsub --language=java --publish=noop
      - run: Build: Speech (Java)
        command: artman --api=speech --language=java --publish=noop
    working_directory: /usr/src/artman/

  nodejs:
    docker: googleapis/artman:latest
    steps:
      - checkout
      - run: Install latest artman
        command: |
          pip uninstall googleapis-artman
          pip install /usr/src/artman/
      - run: Build: Pub/Sub (Node.js)
        command: artman --api=pubsub --language=nodejs --publish=noop
      - run: Build: Speech (Node.js)
        command: artman --api=speech --language=nodejs --publish=noop
    working_directory: /usr/src/artman/

  php:
    docker: googleapis/artman:latest
    steps:
      - checkout
      - run: Install latest artman
        command: |
          pip uninstall googleapis-artman
          pip install /usr/src/artman/
      - run: Build: Pub/Sub (PHP)
        command: artman --api=pubsub --language=php --publish=noop
      - run: Build: Speech (PHP)
        command: artman --api=speech --language=php --publish=noop
    working_directory: /usr/src/artman/

  python:
    docker: googleapis/artman:latest
    steps:
      - checkout
      - run: Install latest artman
        command: |
          pip uninstall googleapis-artman
          pip install /usr/src/artman/
      - run: Build: Pub/Sub (Python)
        command: artman --api=pubsub --language=python --publish=noop
      - run: Unit Tests: Pub/Sub (Python)
        command: |
          cd /artman/output/gapic-google-cloud-pubsub-v1/
          tox -e py35
      - run: Build: Speech (Python)
        command: artman --api=speech --language=python --publish=noop
      - run: Unit Tests: Speech (Python)
        command: |
          cd /artman/output/gapic-google-cloud-speech-v1/
          tox -e py35
    working_directory: /usr/src/artman/

  ruby:
    docker: googleapis/artman:latest
    steps:
      - checkout
      - run: Install latest artman
        command: |
          pip uninstall googleapis-artman
          pip install /usr/src/artman/
      - run: Build: Pub/Sub (Ruby)
        command: artman --api=pubsub --language=ruby --publish=noop
      - run: Build: Speech (Ruby)
        command: artman --api=speech --language=ruby --publish=noop
    working_directory: /usr/src/artman/

workflows:
  version: 2
  tests:
    jobs:
      - csharp
      - go
      - java
      - nodejs
      - php
      - python
      - ruby
